services:
  model1:
    build:
      context: .
      dockerfile: docker/poly-lithic.Dockerfile
    container_name: model1
    volumes:
      - ./test_deployment_1.yaml:/config.yaml
    command: ["model_manager","run","--publish", "-c", "/config.yaml"]
    depends_on:
      - wrangler
    networks:
      - simframe_services_network
  model2:
    build:
      context: .
      dockerfile: docker/poly-lithic.Dockerfile
    container_name: model2
    volumes:
      - ./test_deployment.yaml:/config.yaml
    command:  ["model_manager","run","--publish", "-c", "/config.yaml"]
    depends_on:
      - wrangler
    networks:
      - simframe_services_network
  wrangler:
    container_name: wrangler
    build:
      context: .
      dockerfile: docker/poly-wrangler.Dockerfile
    command: ["python", "/app/simframe_services/wrangler.py", "run" , "--host", "0.0.0.0", "--kafka-broker", "athena.isis.rl.ac.uk:9092"]
    ports:
      - "8012:8000"
    networks:
      - simframe_services_network


networks:
    simframe_services_network:
